apiVersion: v1
kind: List
metadata:
  name: razeedash-api
  namespace: razee
  annotations:
    version: "{{TRAVIS_COMMIT}}"
items:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        version: "{{TRAVIS_COMMIT}}"
        razee.io/git-repo: "{{{GIT_REMOTE}}}"
        razee.io/commit-sha: "{{TRAVIS_COMMIT}}"
      name: razeedash-api
      namespace: razee
    spec:
      replicas: 1
      revisionHistoryLimit: 0
      selector:
        matchLabels:
          app: razeedash-api
      strategy:
        type: RollingUpdate
      template:
        metadata:
          labels:
            app: razeedash-api
          name: razeedash-api
        spec:
          containers:
          - env:
            - name: MONGO_URL
              valueFrom:
                secretKeyRef:
                  name: razeedash-secret
                  key: mongo_url
            - name: MONGO_DB_NAME
              value: razeedash
            image: "quay.io/razee/razeedash-api:{{TRAVIS_TAG}}"
            imagePullPolicy: Always
            name: razeedash-api
            ports:
            - containerPort: 3333
              protocol: TCP
            livenessProbe:
              httpGet:
                path: /api/kube/liveness
                port: 3333
              initialDelaySeconds: 5
              periodSeconds: 10
              timeoutSeconds: 2
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        razee.io/git-repo: "{{{GIT_REMOTE}}}"
        razee.io/commit-sha: "{{TRAVIS_COMMIT}}"
      name:  razeedash-api-service
      namespace: razee
    spec:
      selector:
        app: razeedash-api
      ports:
       - protocol: TCP
         port: 3333
         targetPort: 3333
  - apiVersion: batch/v1beta1
    kind: CronJob
    metadata:
      name: razeedash-api-stats-cron
      namespace: razee
      annotations:
        razee.io/git-repo: "{{{GIT_REMOTE}}}"
        razee.io/commit-sha: "{{TRAVIS_COMMIT}}"
    spec:
      schedule: "*/5 * * * *"
      concurrencyPolicy: Forbid
      successfulJobsHistoryLimit: 1
      failedJobsHistoryLimit: 1
      jobTemplate:
        spec:
          template:
            spec:
              containers:
                - name: api-stats-cron
                  image: buildpack-deps:curl
                  args:
                    - /bin/sh
                    - -ec
                    - curl -X POST http://razeedash-api-service.razee:3333/api/cron/processStats
              restartPolicy: Never
